#!/bin/sh -f


# out_0 is cols=0, rows=0
# out_1 is cols=1, rows=0
# out_2 is cols=2, rows=0
# ...
# and row=0 is bottom of big image.

# output file is out.jpg

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../build_icons/one_screen.jpg out_0.jpg
/bin/cp ../build_icons/one_screen.jpg out_1.jpg
/bin/cp ../build_icons/one_screen.jpg out_2.jpg
/bin/cp ../build_icons/one_screen.jpg out_3.jpg
/bin/cp ../build_icons/one_screen.jpg out_4.jpg
/bin/cp ../build_icons/one_screen.jpg out_5.jpg
/bin/cp ../build_icons/one_screen.jpg out_6.jpg
/bin/cp ../build_icons/one_screen.jpg out_7.jpg
/bin/cp ../build_icons/one_screen.jpg out_8.jpg
/bin/cp ../build_icons/one_screen.jpg out_9.jpg
_jpeg_conc -cols=3 -rows=3
/bin/mv out.jpg wall_screens.jpg
find . -name 'out*.jpg' -exec /bin/rm -f {} \;

exit

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../build_icons/edit_clear.jpg out_0.jpg
/bin/cp ../build_icons/histo.jpg out_1.jpg
_jpeg_conc -cols=2 -rows=1
/bin/mv out.jpg clear_histo.jpg
find . -name 'out*.jpg' -exec /bin/rm -f {} \;

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../build_icons/edit.jpg out_0.jpg
/bin/cp ../build_icons/ioda_cube.jpg out_1.jpg
_jpeg_conc -cols=2 -rows=1
/bin/mv out.jpg edit_geom.jpg
find . -name 'out*.jpg' -exec /bin/rm -f {} \;

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../build_icons/white.jpg out_0.jpg
/bin/cp ../build_icons/white.jpg out_1.jpg
/bin/cp ../build_icons/g4.jpg out_2.jpg
/bin/cp ../build_icons/eye_watch.jpg out_3.jpg
/bin/cp ../build_icons/white.jpg out_4.jpg
/bin/cp ../build_icons/white.jpg out_5.jpg
_jpeg_conc -cols=2 -rows=3
/bin/mv out.jpg g4view_large.jpg
find . -name 'out*.jpg' -exec /bin/rm -f {} \;

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../build_icons/g4.jpg out_0.jpg
/bin/cp ../build_icons/eye_watch.jpg out_1.jpg
_jpeg_conc -cols=2 -rows=1
/bin/mv out.jpg g4view.jpg
/bin/rm -f out_0.jpg out_1.jpg

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../build_icons/g4.jpg out_0.jpg
/bin/cp ../build_icons/tools.jpg out_1.jpg
_jpeg_conc -cols=2 -rows=1
/bin/mv out.jpg g4tools.jpg
/bin/rm -f out_0.jpg out_1.jpg

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../build_icons/kmenuedit.jpg out_0.jpg
/bin/cp ../build_icons/forward.jpg out_1.jpg
/bin/cp ../build_icons/wall_monitor_2x2_128.jpg out_2.jpg
_jpeg_conc -cols=3 -rows=1
/bin/mv out.jpg set_menu_screen.jpg
/bin/rm -f out_0.jpg out_1.jpg out_2.jpg

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../res/close.jpg out_0.jpg
/bin/cp ../build_icons/apple_ipad_glossy.jpg out_1.jpg
_jpeg_conc -cols=2 -rows=1
/bin/mv out.jpg stop_data_client.jpg
/bin/rm -f out_0.jpg out_1.jpg

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../res/close.jpg out_0.jpg
/bin/cp ../build_icons/sidebar_photos.jpg out_1.jpg
_jpeg_conc -cols=2 -rows=1
/bin/mv out.jpg stop_diaporama.jpg
/bin/rm -f out_0.jpg out_1.jpg

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../res/close.jpg out_0.jpg
/bin/cp ../build_icons/forward.jpg out_1.jpg
/bin/cp ../build_icons/wall_monitor_2x2_128.jpg out_2.jpg
_jpeg_conc -cols=3 -rows=1
/bin/mv out.jpg disconnect_from_wall.jpg
/bin/rm -f out_0.jpg out_1.jpg out_2.jpg

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../res/edit_clear.jpg out_0.jpg
/bin/cp ../res/event.jpg out_1.jpg
_jpeg_conc -cols=2 -rows=1
/bin/mv out.jpg clear_event.jpg

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../res/close.jpg out_0.jpg
/bin/cp ../res/event.jpg out_1.jpg
_jpeg_conc -cols=2 -rows=1
/bin/mv out.jpg stop_events.jpg
/bin/rm -f out_0.jpg out_1.jpg

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
/bin/cp ../res/button_forward_01.jpg out_0.jpg
/bin/cp ../res/event.jpg out_1.jpg
_jpeg_conc -cols=2 -rows=1
/bin/mv out.jpg vis_events.jpg
/bin/rm -f out_0.jpg out_1.jpg

#//////////////////////////////////////////////
#//////////////////////////////////////////////
#//////////////////////////////////////////////
