#!/bin/sh -f

#set -x

if test `uname` = "CYGWIN32_NT" ; then
cmd='byacc'
else
if test `uname` = "Darwin" ; then
#cmd='yacc'
cmd='/opt/local/bin/byacc'
else
cmd='/usr/local/byacc/20050813/bin/yacc'
fi
fi

# kmath parser :
echo "${cmd} kmath.y..."
$cmd -d ../source/kmath.yacc
sed 's/yylval/kmathlval/g' y.tab.c > tmp
sed 's/yylex/kmathlex/g' tmp > tmp1
sed 's/yyparse/kmathparse/g' tmp1 > tmp2
sed 's/yyerror/kmatherror/g' tmp2 > tmp3
sed 's/yy/kmath_/g' tmp3 > ../source/kmath.c
#sed 's/yy/kmath_/g' y.tab.h > ../source/kmath_tokens.h
rm -f y.tab.c
rm -f y.tab.h
rm -f tmp tmp1 tmp2 tmp3

