#!/bin/sh -f

bush_home=../../../bush

. ${bush_home}/args
. ${bush_home}/ourex_header

cppflags="${cppflags} -I../CoinPython"

plugin=HEPVis_SWIG_Python
pyname=HEPVis_SWIG_Python

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////
use_archive=no # OpenScientist needs shared libs.

use_inlib=yes
use_HEPVis=yes
use_Python=yes
use_CoinGL=yes
use_GL=yes
use_png=yes
use_jpeg=yes
use_freetype=yes
use_zlib=yes

. ${bush_home}/use/inlib
. ${bush_home}/use/HEPVis
. ${bush_home}/use/Python
. ${bush_home}/use/CoinGL
. ${bush_home}/use/GL
. ${bush_home}/use/png
. ${bush_home}/use/jpeg
. ${bush_home}/use/freetype
. ${bush_home}/use/zlib

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

if [ ${build_compile} = "yes" ] ; then

cxxfiles="${cxxfiles} ./source/Python/HEPVis_SWIG_Python.cxx"

cppflags="${cppflags} -I./include"

if [ ${build_visual} = "yes" ] ; then
  cppflags="${cppflags} -wd4244 -wd4700 -wd4049"
else
  cppflags="${cppflags} -w"
fi

. ${bush_home}/compile

fi # end build_compile

if [ ${build_plugin} = "yes" ] ; then . ${bush_home}/plugin; fi

. ${bush_home}/clean
