#!/bin/sh -f

#  To produce wrappers using SWIG.

bush_home=../../../bush

pivy_home=../pivy

use_swig=yes
. ${bush_home}/use/swig

if [ ! -x ${SWIG_exe} ] ; then
  echo "swig program not found."
  exit
fi

echo "swig program is : ${swig_exe}"

#set -v

HEPVis_home=.

incs="-I${pivy_home} -I${pivy_home}/fake_headers"
incs="${incs} -I${pivy_home}/interfaces"

incs="${incs} -I../CoinGL/include -I${HEPVis_home}/include"
incs="${incs} -I../CoinPython"
incs="${incs} -I../CoinPython/source"
incs="${incs} -I${HEPVis_home}/source/SWIG"
incs="${incs} -I../../inlib -I../../inlib/inlib/histo -I../../inlib/inlib"

flags="-includeall -modern -D__PIVY__"
flags="${flags} -w302,306,307,312,389,361,362,467,503,509,510"
flags="${flags} -DHEPVIS_HAS_TTF2"
flags="${flags} -fcompact"

out_file=${HEPVis_home}/source/Python/HEPVis_SWIG_Python.ic
${swig_exe} -interface HEPVis_SWIG_Python -python -c++ ${flags} ${incs} -o ${out_file} ${HEPVis_home}/source/SWIG/HEPVis_SWIG.i
/bin/mv ${HEPVis_home}/source/Python/HEPVis.py ${HEPVis_home}/scripts/Python/.

sed -e 's#PyErr_Format(PyExc_RuntimeError, mesg)#PyErr_Format(PyExc_RuntimeError, "%s",mesg)#g' ${out_file} > tmp;mv tmp ${out_file}
/bin/rm -f tmp
