#!/bin/sh -f

run_what=

build_args=
while test $# -ge 1 ; do
  case $1 in
    -*) build_args="${build_args} $1";;  
     *) run_what=$1;;  
  esac
  shift
done

bush_home=../../../bush

. ${bush_home}/ourex_header

#////////////////////////////////////
#/// plugins : //////////////////////
#////////////////////////////////////
PYTHONPATH=
PYTHONPATH="${PYTHONPATH}:${build_path}"
PYTHONPATH="${PYTHONPATH}:../CoinPython/${build_dir}"
PYTHONPATH="${PYTHONPATH}:../CoinXt/${build_dir}"
#////////////////////////////////////
#/// .py scripts : //////////////////
#////////////////////////////////////
PYTHONPATH="${PYTHONPATH}:./scripts/Python"
PYTHONPATH="${PYTHONPATH}:../CoinPython/scripts"
PYTHONPATH="${PYTHONPATH}:../CoinXt/py"

# for examples/Python/plotter.py
if [ "${exlib_home}" != "" ] ; then
  PYTHONPATH="${PYTHONPATH}:${exlib_home}/mgr/${build_dir}"
  PYTHONPATH="${PYTHONPATH}:${exlib_home}/exlib/py"
fi

export PYTHONPATH

#////////////////////////////////////
#/// shared libs : //////////////////
#////////////////////////////////////
ld_path=
ld_path="${ld_path}:../CoinXt/${build_dir}"
ld_path="${ld_path}:../HEPVis/${build_dir}"
ld_path="${ld_path}:../CoinGL/${build_dir}"
ld_path="${ld_path}:../freetype/${build_dir}"
ld_path="${ld_path}:../jpeg/${build_dir}"
ld_path="${ld_path}:../png/${build_dir}"
ld_path="${ld_path}:../zlib/${build_dir}"

. ${bush_home}/ld_library_path

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

use_Python=yes
. ${bush_home}/use/Python

if [ "${Python_ld_library_path}" != "" ] ; then
  ld_path="${Python_ld_library_path}"
  . ${bush_home}/ld_library_path
fi

#////////////////////////////////////
#/// run : //////////////////////////
#////////////////////////////////////

if [ "${py_exe}" = "" ] ; then
  echo 'ourex/HEPVis/pyrun : py_exe not defined. Change bush/use/Python.'
  exit
fi

TTFPATH=./fonts
export TTFPATH

if [ "${run_what}" = "" ] ; then run_what=cube; fi

${py_exe} ./examples/Python/${run_what}.py

