#!/bin/sh -f

where=.

grep '#define' ${where}/H5pubconf_Linux.h > conf_linux_le_32.h
grep '#define' ${where}/H5pubconf_Linux_x86_64.h > conf_linux_le_64.h
grep '#define' ${where}/H5pubconf_macosx.h > conf_osx_be_32.h
grep '#define' ${where}/H5pubconf_macosx_intel.h > conf_osx_le_32.h
grep '#define' ${where}/H5pubconf_macosx_x86_64.h > conf_osx_le_64.h

grep '#define' ${where}/H5pubconf_win32.h > conf_win32.h
grep '#define' ${where}/H5pubconf_CYGWIN.h > conf_cygwin.h

