#!/bin/sh -f

save_dir=`pwd`

find ./src -name '*.c' -exec /bin/rm -f {} \;
find ./src -name '*.h' -exec /bin/rm -f {} \;

py_home=../../ourex_zips/Python-2.7.8

mkdir -p ./src/Include
find ${py_home}/Include -maxdepth 1 -name '*.h' -exec cp {} ./src/Include/. \;

mkdir -p ./include/python2.7
find ${py_home}/Include -maxdepth 1 -name '*.h' -exec cp {} ./include/python2.7/. \;

mkdir -p ./src/Python
find ${py_home}/Python -maxdepth 1 -name '*.h' -exec cp {} ./src/Python/. \;
find ${py_home}/Python -maxdepth 1 -name '*.c' -exec cp {} ./src/Python/. \;

mkdir -p ./src/Parser
find ${py_home}/Parser -maxdepth 1 -name '*.h' -exec cp {} ./src/Parser/. \;
find ${py_home}/Parser -maxdepth 1 -name '*.c' -exec cp {} ./src/Parser/. \;

mkdir -p ./src/Objects/stringlib
find ${py_home}/Objects/stringlib -maxdepth 1 -name '*.h' -exec cp {} ./src/Objects/stringlib/. \;
find ${py_home}/Objects -maxdepth 1 -name '*.h' -exec cp {} ./src/Objects/. \;
find ${py_home}/Objects -maxdepth 1 -name '*.c' -exec cp {} ./src/Objects/. \;

mkdir -p ./src/Modules
items="getpath main gcmodule threadmodule  signalmodule  posixmodule  errnomodule  pwdmodule"
items="${items} _sre  _codecsmodule  _weakref  zipimport  symtablemodule  xxsubtype"
items="${items} getbuildinfo"
items="${items} python"
items="${items} mathmodule cmathmodule _math"
# enforced builtin :
items="${items} operator _functoolsmodule _localemodule"

for item in ${items} ; do
  /bin/cp ${py_home}/Modules/${item}.c ./src/Modules/.
done
find ${py_home}/Modules -maxdepth 1 -name '*.h' -exec cp {} ./src/Modules/. \;

mkdir -p ./src/PC
/bin/cp ${py_home}/PC/errmap.h ./src/PC/.
/bin/cp ${py_home}/PC/frozen_dllmain.c ./src/PC/.

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
find ./src/Python -maxdepth 1 -name 'dynload*.c' -exec /bin/rm -f {} \;
/bin/cp ${py_home}/Python/dynload_shlib.c ./src/Python/.

/bin/rm -f ./src/Python/sigcheck.c
/bin/rm -f ./src/Parser/intrcheck.c

# pgen program :
/bin/rm -f ./src/Parser/tokenizer_pgen.c
/bin/rm -f ./src/Parser/printgrammar.c
/bin/rm -f ./src/Parser/pgenmain.c

#//////////////////////////////////////////////////////
#/// lib/python2.7 ////////////////////////////////////
#//////////////////////////////////////////////////////
find ./lib -name '*.py*' -exec /bin/rm -f {} \;
mkdir -p ./lib/python2.7/lib-dynload
items="copy_reg genericpath linecache os posixpath ntpath locale"
#items="${items} _sysconfigdata"
items="${items} re site sre_compile sre_constants sre_parse stat sysconfig traceback types warnings"
items="${items} codecs functools"
items="${items} _osx_support"

items="${items} UserDict _abcoll abc _weakrefset" #for osc_onx_coin/mgr/pyrun.

for item in ${items} ; do
  /bin/cp ${py_home}/Lib/${item}.py ./lib/python2.7/.
done
mkdir -p ./lib/python2.7/encodings
/bin/cp ${py_home}/Lib/encodings/__init__.py ./lib/python2.7/encodings/.
/bin/cp ${py_home}/Lib/encodings/aliases.py ./lib/python2.7/encodings/.
/bin/cp ${py_home}/Lib/encodings/utf_8.py ./lib/python2.7/encodings/.
/bin/cp ${py_home}/Lib/encodings/cp850.py ./lib/python2.7/encodings/.

/bin/cp ./modified/pyconfig.h ./src/.
/bin/cp ./modified/pyconfig.h ./include/python2.7/.

/bin/cp ./modified/pystrtod.c ./src/Python/.

/bin/cp ./modified/localeutil.h ./src/Objects/stringlib/.
/bin/cp ./modified/formatter.h ./src/Objects/stringlib/.
/bin/cp ./modified/fileobject.c ./src/Objects/.

/bin/cp ./modified/pwdmodule.c ./src/Modules/.
/bin/cp ./modified/getpath.c ./src/Modules/.
/bin/cp ./modified/config.c ./src/Modules/.
/bin/cp ./modified/_localemodule.c ./src/Modules/.
/bin/cp ./modified/posixmodule.c ./src/Modules/.
/bin/cp ./modified/signalmodule.c ./src/Modules/.
/bin/cp ./modified/fileobject.h ./src/Include/.
/bin/cp ./modified/fileobject.h ./include/python2.7/.

/bin/cp ./modified/_sysconfigdata.py ./lib/python2.7/_sysconfigdata.py

/bin/cp ./modified/bytearrayobject.c ./src/Objects/.
/bin/mv ./src/Objects/stringlib/ctype.h ./src/Objects/stringlib/gb_ctype.h 

#/bin/cp ./modified/import.c ./src/Python/.
