#!/bin/sh -f

save_dir=`pwd`

find ./src -name '*.c' -exec /bin/rm -f {} \;
find ./src -name '*.h' -exec /bin/rm -f {} \;

find ./apps -name '*.c' -exec /bin/rm -f {} \;

home_dir=../../ourex_zips/lua-5.2.0

mkdir -p ./src
find ${home_dir}/src -maxdepth 1 -name '*.h' -exec cp {} ./src/. \;
find ${home_dir}/src -maxdepth 1 -name '*.c' -exec cp {} ./src/. \;

mkdir -p ./apps
/bin/mv ./src/lua.c ./apps/.
/bin/mv ./src/luac.c ./apps/.

/bin/cp ./modified/llex.c ./src/.
/bin/cp ./modified/loslib.c ./src/.
/bin/cp ./modified/luaconf.h ./src/.

cd ${save_dir}
