
LOCAL_PATH := $(call my-dir)

#/////////////////////////////////
#/// CoinGL : ////////////////////
#/////////////////////////////////
include $(CLEAR_VARS)
OUREX_DIR := ../../../inexlib/ourex
LOCAL_MODULE := ourex_CoinGL
LOCAL_SRC_FILES := $(OUREX_DIR)/CoinGL/bin_sdk_android/libourex_CoinGL.a
include $(PREBUILT_STATIC_LIBRARY)

#/////////////////////////////////
#/// HEPVis : ////////////////////
#/////////////////////////////////
include $(CLEAR_VARS)
OUREX_DIR := ../../../inexlib/ourex
LOCAL_MODULE := ourex_HEPVis
LOCAL_SRC_FILES := $(OUREX_DIR)/HEPVis/bin_sdk_android/libourex_HEPVis.a
include $(PREBUILT_STATIC_LIBRARY)
#/////////////////////////////////
#/////////////////////////////////
#/////////////////////////////////

include $(CLEAR_VARS)

LOCAL_MODULE := ioda

LOCAL_CPP_EXTENSION := .cpp .cc

# -DINLIB_MEM
# -DINLIB_USE_CSZ : for inlib_swig_[lua,py].cpp
# -DEXLIB_ANDROID_MAIN_DO_STD_EXIT : else problem with Python lib unfolding when stopping/restarting the app.
#                                    See note in main.cpp.

LOCAL_CPPFLAGS := -fexceptions -frtti  # for SOPHIA headers.

INEXLIB_INC := ../../inexlib
INEXLIB_SRC := ../../../inexlib

LOCAL_CFLAGS := \
 -DEXLIB_ANDROID_MAIN_DO_STD_EXIT\
 -DEXLIB_HAS_GL_VBO\
 -DINLIB_USE_CSZ\
 -DAPP_USE_EDEP\
 -DAPP_USE_SOPHYA\
 -DAPP_USE_DCMTK\
 -DAPP_USE_PYTHON\
 -DNDEBUG -DPy_BUILD_CORE\
 -DAPP_USE_HIV\
 -DAPP_USE_GOPAW\
\
 -I$(INEXLIB_INC)/inlib\
 -I$(INEXLIB_INC)/exlib\
 \
 -I$(INEXLIB_INC)/ourex/expat/include\
 \
 -I$(INEXLIB_INC)/ourex/freetype/include\
 -I$(INEXLIB_INC)/ourex/freetype/include/freetype\
 -I$(INEXLIB_INC)/ourex/freetype/src/builds\
 \
 -I$(INEXLIB_INC)/ourex/jpeg/jpeg\
 \
 -I$(INEXLIB_INC)/ourex/png/png\
 \
 -I$(INEXLIB_INC)/ourex/cfitsio/include\
 \
 -I$(INEXLIB_INC)/ourex/gl2ps\
 \
 -I$(INEXLIB_INC)/ourex/hdf5/include\
 \
 -I$(INEXLIB_INC)/ourex/graphviz\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/cdt\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/graph\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/xdot\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/common\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/sparse\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/pack\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/neatogen\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/fdpgen\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/pathplan\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/gvc\
 -I$(INEXLIB_INC)/ourex/graphviz/lib/dotgen\
 \
 -I$(INEXLIB_INC)/ourex/SOPHYA/include\
 \
 -I$(INEXLIB_INC)/ourex/dcmtk/config/include\
 -I$(INEXLIB_INC)/ourex/dcmtk/ofstd/include\
 -I$(INEXLIB_INC)/ourex/dcmtk/oflog/include\
 -I$(INEXLIB_INC)/ourex/dcmtk/dcmdata/include\
 -I$(INEXLIB_INC)/ourex/dcmtk/dcmimgle/include\
 -I$(INEXLIB_INC)/ourex/dcmtk/dcmimage/include\
 \
 -I$(INEXLIB_INC)/ourex/zlib/include\
 \
 -I$(INEXLIB_INC)/ourex/zip/include\
 \
 -I$(INEXLIB_INC)/ourex/lua/src\
 \
 -I$(INEXLIB_INC)/ourex/wcslib/include/wcslib\
 \
 -I$(INEXLIB_INC)/ourex/Python/include/python2.7\
 \
 -I$(INEXLIB_INC)/ourex/KUIP/include\
 \
 -I$(INEXLIB_INC)/ourex/CoinGL/include\
 -I$(INEXLIB_INC)/ourex/HEPVis/include

EXPAT_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/expat/source/xmlparse.cpp\
 $(INEXLIB_SRC)/ourex/expat/source/xmlrole.cpp\
 $(INEXLIB_SRC)/ourex/expat/source/xmltok.cpp

FREETYPE_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/freetype/src/builds/unix/ftsystem.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftdebug.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftinit.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftbase.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftbbox.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftbdf.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftglyph.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftmm.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftpfr.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftstroke.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/fttype1.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftwinfnt.c\
 $(INEXLIB_SRC)/ourex/freetype/src/base/ftxf86.c\
 $(INEXLIB_SRC)/ourex/freetype/src/gzip/ftgzip.c\
 $(INEXLIB_SRC)/ourex/freetype/src/autohint/autohint.c\
 $(INEXLIB_SRC)/ourex/freetype/src/bdf/bdf.c\
 $(INEXLIB_SRC)/ourex/freetype/src/cache/ftcache.c\
 $(INEXLIB_SRC)/ourex/freetype/src/cff/cff.c\
 $(INEXLIB_SRC)/ourex/freetype/src/cid/type1cid.c\
 $(INEXLIB_SRC)/ourex/freetype/src/lzw/ftlzw.c\
 $(INEXLIB_SRC)/ourex/freetype/src/pcf/pcf.c\
 $(INEXLIB_SRC)/ourex/freetype/src/pfr/pfr.c\
 $(INEXLIB_SRC)/ourex/freetype/src/psaux/psaux.c\
 $(INEXLIB_SRC)/ourex/freetype/src/pshinter/pshinter.c\
 $(INEXLIB_SRC)/ourex/freetype/src/psnames/psmodule.c\
 $(INEXLIB_SRC)/ourex/freetype/src/raster/raster.c\
 $(INEXLIB_SRC)/ourex/freetype/src/sfnt/sfnt.c\
 $(INEXLIB_SRC)/ourex/freetype/src/smooth/smooth.c\
 $(INEXLIB_SRC)/ourex/freetype/src/truetype/truetype.c\
 $(INEXLIB_SRC)/ourex/freetype/src/type1/type1.c\
 $(INEXLIB_SRC)/ourex/freetype/src/type42/type42.c\
 $(INEXLIB_SRC)/ourex/freetype/src/winfonts/winfnt.c

ZIP_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/zip/source/zip.c\
 $(INEXLIB_SRC)/ourex/zip/source/unzip.c\
 $(INEXLIB_SRC)/ourex/zip/source/ioapi.c

JPEG_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/jpeg/source/cdjpeg.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcapimin.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcapistd.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jccoefct.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jccolor.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcdctmgr.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jchuff.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcinit.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcmainct.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcmarker.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcmaster.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcomapi.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcparam.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcphuff.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcprepct.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jcsample.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jctrans.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdapimin.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdapistd.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdatadst.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdatasrc.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdcoefct.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdcolor.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jddctmgr.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdhuff.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdinput.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdmainct.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdmarker.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdmaster.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdmerge.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdphuff.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdpostct.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdsample.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jdtrans.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jerror.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jfdctflt.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jfdctfst.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jfdctint.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jidctflt.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jidctfst.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jidctint.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jidctred.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jmemansi.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jmemmgr.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jquant1.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jquant2.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/jutils.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/rdbmp.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/rdcolmap.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/rdgif.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/rdppm.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/rdrle.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/rdswitch.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/rdtarga.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/transupp.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/wrbmp.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/wrgif.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/wrppm.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/wrrle.c\
 $(INEXLIB_SRC)/ourex/jpeg/source/wrtarga.c

PNG_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/png/source/png.c\
 $(INEXLIB_SRC)/ourex/png/source/pngerror.c\
 $(INEXLIB_SRC)/ourex/png/source/pngget.c\
 $(INEXLIB_SRC)/ourex/png/source/pngmem.c\
 $(INEXLIB_SRC)/ourex/png/source/pngpread.c\
 $(INEXLIB_SRC)/ourex/png/source/pngread.c\
 $(INEXLIB_SRC)/ourex/png/source/pngrio.c\
 $(INEXLIB_SRC)/ourex/png/source/pngrtran.c\
 $(INEXLIB_SRC)/ourex/png/source/pngrutil.c\
 $(INEXLIB_SRC)/ourex/png/source/pngset.c\
 $(INEXLIB_SRC)/ourex/png/source/pngtrans.c\
 $(INEXLIB_SRC)/ourex/png/source/pngwio.c\
 $(INEXLIB_SRC)/ourex/png/source/pngwrite.c\
 $(INEXLIB_SRC)/ourex/png/source/pngwtran.c\
 $(INEXLIB_SRC)/ourex/png/source/pngwutil.c

CFITSIO_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/cfitsio/src/buffers.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/cfileio.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/checksum.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/compress.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/drvrfile.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/drvrmem.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/editcol.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/edithdu.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/eval_l.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/eval_y.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/eval_f.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/fitscore.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcol.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcolb.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcold.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcole.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcoli.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcolj.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcolk.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcoll.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcols.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcolsb.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcoluk.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcolui.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getcoluj.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/getkey.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/group.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/grparser.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/histo.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/iraffits.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/modkey.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcol.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcolb.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcold.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcole.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcoli.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcolj.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcolk.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcoluk.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcoll.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcols.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcolsb.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcolu.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcolui.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putcoluj.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/putkey.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/region.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/scalnull.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/swapproc.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/wcssub.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/wcsutil.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/imcompress.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/quantize.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/ricecomp.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/pliocomp.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/fits_hcompress.c\
 $(INEXLIB_SRC)/ourex/cfitsio/src/fits_hdecompress.c

HDF5_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/hdf5/src/H5.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5A.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5AC.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5B.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5C.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5D.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Dcompact.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Dcontig.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Defl.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Dio.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Distore.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Dmpio.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Dselect.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Dtest.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5E.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5F.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FD.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Fdbg.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDcore.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDfamily.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDgass.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDlog.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDmpi.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDmpio.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDmpiposix.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDmulti.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDsec2.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDsrb.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDstdio.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FDstream.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FL.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Fmount.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FO.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5FS.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Fsfile.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Fsuper.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5G.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Gent.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Gnode.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Gstab.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5HG.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5HGdbg.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5HL.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5HLdbg.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5HP.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5I.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5MF.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5MM.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5O.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Oattr.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Obogus.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Ocont.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Odtype.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Oefl.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Ofill.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Olayout.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Omtime.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Oname.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Onull.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Opline.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Osdspace.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Oshared.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Ostab.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5P.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Pdcpl.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Pdxpl.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Pfapl.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Pfcpl.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Ptest.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5R.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5RC.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5RS.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5S.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Sall.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Shyper.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5SL.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Smpio.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Snone.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Spoint.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Sselect.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5ST.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Stest.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5T.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tarray.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tbit.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tcommit.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tcompound.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tconv.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tcset.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tenum.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tfields.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tfixed.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tfloat.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tinit.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tnative.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Toffset.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Topaque.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Torder.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tpad.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tprecis.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5TS.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tstrpad.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Tvlen.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5V.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Z.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Zdeflate.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Zfletcher32.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Zshuffle.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/H5Zszip.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/hl/H5IM.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/hl/H5LT.c\
 $(INEXLIB_SRC)/ourex/hdf5/src/hl/H5TA.c

GRAPHVIZ_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtclose.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtdisc.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtextract.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtflatten.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dthash.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtlist.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtmethod.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtopen.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtrenew.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtrestore.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtsize.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtstat.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtstrhash.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dttree.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dttreeset.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtview.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/cdt/dtwalk.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/args.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/arrows.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/colxlate.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/emit.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/fontmetrics.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/geom.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/globals.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/htmllex.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/htmlparse.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/htmltable.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/input.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/labels.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/memory.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/ns.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/output.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/pointset.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/postproc.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/psusershape.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/routespl.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/shapes.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/splines.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/timing.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/common/utils.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/acyclic.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/aspect.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/class1.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/class2.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/cluster.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/compound.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/conc.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/decomp.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/dotinit.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/dotsplines.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/fastgr.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/flat.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/mincross.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/position.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/rank.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/dotgen/sameport.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/fdpgen/clusteredges.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/fdpgen/comp.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/fdpgen/fdpinit.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/fdpgen/grid.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/fdpgen/layout.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/fdpgen/tlayout.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/fdpgen/xlayout.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/graph/agxbuf.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/graph/attribs.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/graph/edge.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/graph/graph.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/graph/graphio.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/graph/lexer.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/graph/node.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/graph/parser.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/graph/refstr.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/graph/trie.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvc.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvconfig.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvcontext.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvdevice.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvevent.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvjobs.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvlayout.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvloadimage.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvplugin.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvrender.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvtextlayout.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/gvc/gvusershape.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/adjust.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/bfs.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/call_tri.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/circuit.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/closest.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/conjgrad.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/constraint.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/delaunay.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/dijkstra.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/edges.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/embed_graph.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/geometry.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/heap.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/hedges.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/info.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/kkutils.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/legal.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/lu.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/matinv.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/matrix_ops.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/memory.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/multispline.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/neatoinit.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/neatosplines.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/overlap.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/pca.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/poly.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/printvis.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/site.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/solve.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/stress.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/stuff.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/neatogen/voronoi.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pack/ccomps.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pack/pack.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pathplan/cvt.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pathplan/inpoly.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pathplan/route.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pathplan/shortest.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pathplan/shortestpth.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pathplan/solvers.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pathplan/triang.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pathplan/util.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/pathplan/visibility.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/sparse/BinaryHeap.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/sparse/general.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/sparse/IntStack.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/sparse/SparseMatrix.c\
 $(INEXLIB_SRC)/ourex/graphviz/lib/xdot/xdot.c\
 $(INEXLIB_SRC)/ourex/graphviz/plugin/core/gvrender_core_dot.c\
 $(INEXLIB_SRC)/ourex/graphviz/plugin/dot_layout/gvlayout_dot_layout.c

SOPHYA_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/datatype.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/dvlist.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/fiondblock.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/mutyv.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/ndatablock.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/pexceptions.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/ppersist.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/ppfbinstream.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/ppftpointerio.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/rawstream.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/stsrand.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/timestamp.cc\
\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/sunitpcst.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/pqnumber.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/randinterf.cc\
\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/HiStats/basedtable.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/HiStats/datatable.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/HiStats/ntupintf.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/HiStats/ntuple.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/HiStats/swppfdtable.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/HiStats/dtcellrowcont.cc\
\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/FitsIOServer/fitsbntbllineRW.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/FitsIOServer/fitsfile.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/FitsIOServer/fitshdtable.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/FitsIOServer/fitsinoutfile.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/FitsIOServer/fitsntuple.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/FitsIOServer/swfitsdtable.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/TArray/basarr.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/TArray/tarray.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/TArray/tmatrix.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/TArray/tvector.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/TArray/utilarr.cc\
\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/TArray/fioarr.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/TArray/sopemtx.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/FitsIOServer/fitsmanager.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/FitsIOServer/fitshistos.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/HiStats/hisprof.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/HiStats/histos2.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/HiStats/histos.cc\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/NTools/poly.cc\
\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/BaseTools/gnumd5.c\
 $(INEXLIB_SRC)/ourex/SOPHYA/src/SUtils/strutil.c

DCMTK_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/cmdlnarg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcbytstr.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcchrstr.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dccodec.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcdatset.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcddirif.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcdicdir.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcdicent.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcdict.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcdictbi.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcdirrec.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcelem.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcerror.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcfilefo.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dchashdi.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcistrma.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcistrmb.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcistrmf.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcistrmz.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcitem.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dclist.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcmetinf.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcobject.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcostrma.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcostrmb.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcostrmf.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcostrmz.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcpath.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcpcache.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcpixel.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcpixseq.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcpxitem.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcrleccd.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcrlecce.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcrlecp.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcrledrg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcrleerg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcrlerp.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcsequen.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcstack.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcswap.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dctag.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dctagkey.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dctypes.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcuid.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvm.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvr.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrae.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvras.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrat.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrcs.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrda.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrds.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrdt.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrfd.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrfl.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvris.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrlo.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrlt.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrobow.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrof.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrpn.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrpobw.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrsh.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrsl.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrss.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrst.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrtm.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrui.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrul.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrulup.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrus.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcvrut.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcwcache.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/dcxfer.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/vrscan.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diargimg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/dicmyimg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/dicoimg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/dicoopx.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/dicopx.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/dihsvimg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/dilogger.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/dipalimg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/dipipng.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/dipitiff.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diqtctab.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diqtfs.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diqthash.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diqthitl.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diqtpbox.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diquant.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diregist.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/dirgbimg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diybrimg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diyf2img.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimage/libsrc/diyp2img.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dcmimage.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dibaslut.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/diciefn.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dicielut.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/didislut.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/didispfn.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/didocu.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/digsdfn.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/digsdlut.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/diimage.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/diinpx.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/diluptab.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dimo1img.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dimo2img.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dimoimg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dimoimg3.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dimoimg4.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dimoimg5.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dimomod.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dimoopx.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/dimopx.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/diovdat.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/diovlay.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/diovlimg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/diovpln.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmimgle/libsrc/diutils.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/apndimpl.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/appender.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/config.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/consap.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/factory.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/fileap.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/filter.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/globinit.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/hierarchy.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/hierlock.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/layout.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/lloguser.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/logevent.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/logger.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/logimpl.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/loglevel.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/loglog.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/ndc.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/ntelogap.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/nullap.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/objreg.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/oflog.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/patlay.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/pointer.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/property.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/rootlog.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/sleep.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/sockbuff.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/socket.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/socketap.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/strhelp.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/syncprims.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/syslogap.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/timehelp.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/oflog/libsrc/unixsock.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofcmdln.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofconapp.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofcond.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofconfig.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofconsol.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofcrc32.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofdate.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofdatime.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/offname.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/oflist.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofstd.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofstring.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/ofthread.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/ofstd/libsrc/oftime.cc\
 $(INEXLIB_SRC)/ourex/dcmtk/dcmdata/libsrc/vrscanl.c

CSZ_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/csz/src/inflate.c

GL2PS_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/gl2ps/source/gl2ps.c

# zlib :
#LOCAL_CFLAGS += -DEXLIB_USE_NATIVE_ZLIB
#LOCAL_CXXFLAGS += -DEXLIB_USE_NATIVE_ZLIB
ZLIB_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/zlib/source/adler32.c\
 $(INEXLIB_SRC)/ourex/zlib/source/compress.c\
 $(INEXLIB_SRC)/ourex/zlib/source/crc32.c\
 $(INEXLIB_SRC)/ourex/zlib/source/deflate.c\
 $(INEXLIB_SRC)/ourex/zlib/source/gzio.c\
 $(INEXLIB_SRC)/ourex/zlib/source/infblock.c\
 $(INEXLIB_SRC)/ourex/zlib/source/infcodes.c\
 $(INEXLIB_SRC)/ourex/zlib/source/inffast.c\
 $(INEXLIB_SRC)/ourex/zlib/source/inflate.c\
 $(INEXLIB_SRC)/ourex/zlib/source/inftrees.c\
 $(INEXLIB_SRC)/ourex/zlib/source/infutil.c\
 $(INEXLIB_SRC)/ourex/zlib/source/trees.c\
 $(INEXLIB_SRC)/ourex/zlib/source/uncompr.c\
 $(INEXLIB_SRC)/ourex/zlib/source/zutil.c

WCSLIB_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/wcslib/src/cel.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/fitshdr.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/lin.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/log.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/prj.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/spc.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/sph.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/spx.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/tab.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcs.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcsbth.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcserr.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcsfix.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcshdr.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcspih.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcsprintf.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcstrig.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcsulex.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcsunits.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcsutil.c\
 $(INEXLIB_SRC)/ourex/wcslib/src/wcsutrn.c

LUA_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/lua/src/lapi.c\
 $(INEXLIB_SRC)/ourex/lua/src/lauxlib.c\
 $(INEXLIB_SRC)/ourex/lua/src/lbaselib.c\
 $(INEXLIB_SRC)/ourex/lua/src/lbitlib.c\
 $(INEXLIB_SRC)/ourex/lua/src/lcode.c\
 $(INEXLIB_SRC)/ourex/lua/src/lcorolib.c\
 $(INEXLIB_SRC)/ourex/lua/src/lctype.c\
 $(INEXLIB_SRC)/ourex/lua/src/ldblib.c\
 $(INEXLIB_SRC)/ourex/lua/src/ldebug.c\
 $(INEXLIB_SRC)/ourex/lua/src/ldo.c\
 $(INEXLIB_SRC)/ourex/lua/src/ldump.c\
 $(INEXLIB_SRC)/ourex/lua/src/lfunc.c\
 $(INEXLIB_SRC)/ourex/lua/src/lgc.c\
 $(INEXLIB_SRC)/ourex/lua/src/linit.c\
 $(INEXLIB_SRC)/ourex/lua/src/liolib.c\
 $(INEXLIB_SRC)/ourex/lua/src/llex.c\
 $(INEXLIB_SRC)/ourex/lua/src/lmathlib.c\
 $(INEXLIB_SRC)/ourex/lua/src/lmem.c\
 $(INEXLIB_SRC)/ourex/lua/src/loadlib.c\
 $(INEXLIB_SRC)/ourex/lua/src/lobject.c\
 $(INEXLIB_SRC)/ourex/lua/src/lopcodes.c\
 $(INEXLIB_SRC)/ourex/lua/src/loslib.c\
 $(INEXLIB_SRC)/ourex/lua/src/lparser.c\
 $(INEXLIB_SRC)/ourex/lua/src/lstate.c\
 $(INEXLIB_SRC)/ourex/lua/src/lstring.c\
 $(INEXLIB_SRC)/ourex/lua/src/lstrlib.c\
 $(INEXLIB_SRC)/ourex/lua/src/ltable.c\
 $(INEXLIB_SRC)/ourex/lua/src/ltablib.c\
 $(INEXLIB_SRC)/ourex/lua/src/ltm.c\
 $(INEXLIB_SRC)/ourex/lua/src/lundump.c\
 $(INEXLIB_SRC)/ourex/lua/src/lvm.c\
 $(INEXLIB_SRC)/ourex/lua/src/lzio.c

PYTHON_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/Python/src/Objects/abstract.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/boolobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/bufferobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/bytearrayobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/bytes_methods.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/capsule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/cellobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/classobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/cobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/codeobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/complexobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/descrobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/dictobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/enumobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/exceptions.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/fileobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/floatobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/frameobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/funcobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/genobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/intobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/iterobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/listobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/longobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/memoryobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/methodobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/moduleobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/object.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/obmalloc.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/rangeobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/setobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/sliceobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/stringobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/structseq.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/tupleobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/typeobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/unicodectype.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/unicodeobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Objects/weakrefobject.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/acceler.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/bitset.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/firstsets.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/grammar.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/grammar1.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/listnode.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/metagrammar.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/myreadline.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/node.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/parser.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/parsetok.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/pgen.c\
 $(INEXLIB_SRC)/ourex/Python/src/Parser/tokenizer.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/_warnings.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/asdl.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/ast.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/atof.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/bltinmodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/ceval.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/codecs.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/compile.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/dtoa.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/dup2.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/dynload_shlib.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/errors.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/formatter_string.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/formatter_unicode.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/frozen.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/frozenmain.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/future.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/getargs.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/getcompiler.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/getcopyright.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/getopt.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/getplatform.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/getversion.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/graminit.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/import.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/importdl.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/marshal.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/modsupport.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/mysnprintf.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/mystrtoul.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/peephole.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/pyarena.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/pyctype.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/pyfpe.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/pymath.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/pystate.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/pystrcmp.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/pystrtod.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/Python-ast.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/pythonrun.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/random.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/structmember.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/symtable.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/sysmodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/thread.c\
 $(INEXLIB_SRC)/ourex/Python/src/Python/traceback.c\
\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/_codecsmodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/_sre.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/_weakref.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/config.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/errnomodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/gcmodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/main.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/posixmodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/pwdmodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/signalmodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/symtablemodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/threadmodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/xxsubtype.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/zipimport.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/operator.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/_localemodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/_functoolsmodule.c\
\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/getpath.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/getbuildinfo.c\
\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/_math.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/cmathmodule.c\
 $(INEXLIB_SRC)/ourex/Python/src/Modules/mathmodule.c

YACC_SRC_FILES := \
  $(INEXLIB_SRC)/exlib/exlib/yacc/cexpr_lexer.cpp\
  $(INEXLIB_SRC)/exlib/exlib/yacc/cexpr_eval.cpp

SLUA_SRC_FILES := \
  $(INEXLIB_SRC)/exlib/exlib/slua/inlib_swig_lua.cpp

SPY_SRC_FILES := \
  $(INEXLIB_SRC)/exlib/exlib/spy/inlib_swig_py.cpp

IV_SRC_FILES := \
 $(INEXLIB_SRC)/exlib/exlib/iv/so_2sg_action.cpp

KUIP_SRC_FILES := \
 $(INEXLIB_SRC)/ourex/KUIP/source/kalias.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kdummy.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kedit.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kexec.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/khash.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kienbr.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kkern.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kmacro.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kmath.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kmenu.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kmisc.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kmterm.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kmutil.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kout.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kstrtod.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kuinit.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kuipcdf.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kutrue.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kuwhat.c\
 $(INEXLIB_SRC)/ourex/KUIP/source/kvect.c

GOPAW_SRC_FILES := \
 $(INEXLIB_SRC)/../gopaw/source/PAWCDF.c\
 $(INEXLIB_SRC)/../gopaw/source/gopawcdf.c\
 $(INEXLIB_SRC)/../gopaw/source/PAW.cpp\
 $(INEXLIB_SRC)/exlib/exlib/yacc/fort_fmt_lexer.cpp\
 $(INEXLIB_SRC)/exlib/exlib/yacc/fort_fmt.cpp

LOCAL_SRC_FILES := \
 $(GOPAW_SRC_FILES)\
 $(KUIP_SRC_FILES)\
 $(ZIP_SRC_FILES)\
 $(GRAPHVIZ_SRC_FILES)\
 $(FREETYPE_SRC_FILES)\
 $(JPEG_SRC_FILES)\
 $(ZLIB_SRC_FILES)\
 $(PNG_SRC_FILES)\
 $(GL2PS_SRC_FILES)\
 $(CFITSIO_SRC_FILES)\
 $(CSZ_SRC_FILES)\
 $(HDF5_SRC_FILES)\
 $(EXPAT_SRC_FILES)\
 $(SOPHYA_SRC_FILES)\
 $(DCMTK_SRC_FILES)\
 $(WCSLIB_SRC_FILES)\
 $(YACC_SRC_FILES)\
 $(LUA_SRC_FILES)\
 $(SLUA_SRC_FILES)\
 $(PYTHON_SRC_FILES)\
 $(SPY_SRC_FILES)\
 $(IV_SRC_FILES)\
 ../main.cpp

LOCAL_LDLIBS := -llog -landroid -lEGL -lGLESv1_CM

LOCAL_STATIC_LIBRARIES := ourex_HEPVis ourex_CoinGL android_native_app_glue

include $(BUILD_SHARED_LIBRARY)

$(call import-module,android/native_app_glue)
