#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file bush.license for terms.

if [ `uname` = Darwin ] ; then
  ip="`ifconfig en0 | grep 'inet ' | awk '{print $2}'`"
  #echo ${ip}
  DISPLAY=${ip}:0;export DISPLAY
  xhost + ${ip}

  args=
  args="-e DISPLAY=${DISPLAY} -v /tmp/.X11-unix:/tmp/.X11-unix:rw"

 #args="${args} -v /tmp/work_dir:/root/Documents/ioda:rw"

  docker run ${args} gbarrand/ioda:1.14.0

else
  echo "Don't know (yet) how to run a docker X11 application on this platform."
fi

