#!/bin/sh -f

if [ ! -f c_tmp ] ; then
  echo 'c_tmp not found.'
  exit
fi

if [ ! -f cpp_tmp ] ; then
  echo 'cpp_tmp not found.'
  exit
fi

save_dir="`pwd`"

cd src

/bin/rm -f xcode_all_c.c
for item in $(cat ../c_tmp) ; do
  line='#include "'${item}'"'
  echo ${line} >> xcode_all_c.c
done

/bin/rm -f xcode_all_cpp.cpp
for item in $(cat ../cpp_tmp) ; do
  line='#include "'${item}'"'
  echo ${line} >> xcode_all_cpp.cpp
done

cd ${save_dir}
