/* include/config.h.  Generated by configure.  */
/* include/discard.h.in.  Generated from configure.ac by autoheader.  */


#ifndef COIN_INTERNAL
#error this is a private header file
#endif

#include <unconfig.h>
#include "setup.h"

#define COIN_CONFIGURE_BUILD I686_PC_LINUX_GNU
#define COIN_CONFIGURE_HOST I686_PC_LINUX_GNU
#define COIN_CONFIGURE_TARGET I686_PC_LINUX_GNU

#define COIN_MAJOR_VERSION 2
#define COIN_MICRO_VERSION 4
#define COIN_MINOR_VERSION 4
#define COIN_VERSION "2.4.4"

#define PACKAGE "Coin"
#define PACKAGE_BUGREPORT "coin-support@coin3d.org"
#define PACKAGE_NAME "Coin"
#define PACKAGE_STRING "Coin 2.4.4"
#define PACKAGE_TARNAME "coin"
#define PACKAGE_VERSION "2.4.4"

#define VERSION "2.4.4"

#define COIN_INT16_T int16_t
#define COIN_INT32_T int32_t
#define COIN_INT64_T int64_t
#define COIN_INT8_T int8_t
#define COIN_INTPTR_T intptr_t

#define COIN_UINT16_T uint16_t
#define COIN_UINT32_T uint32_t
#define COIN_UINT64_T uint64_t
#define COIN_UINT8_T uint8_t
#define COIN_UINTPTR_T uintptr_t

#define HAVE_CPP_COMPILER_FUNCTION_NAME_VAR __func__
#define HAVE_C_COMPILER_FUNCTION_NAME_VAR __func__

#define HAVE_INT16_T 1
#define HAVE_INT32_T 1
#define HAVE_INT64_T 1
#define HAVE_INT8_T 1
#define HAVE_INTPTR_T 1
#define HAVE_INTTYPES_H 1

#define HAVE_UINT16_T 1
#define HAVE_UINT32_T 1
#define HAVE_UINT64_T 1
#define HAVE_UINT8_T 1
#define HAVE_UINTPTR_T 1

#define HAVE_LIBGEN_H 1
#define HAVE_MEMORY_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIMEB_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_UNISTD_H 1
#define HAVE_TIME_H 1
#define HAVE_UNISTD_H 1

#define HAVE_FINITE 1
#define HAVE_FSTAT 1
#define HAVE_FTIME 1
#define HAVE_GETCWD 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_GZDOPEN 1
#define HAVE_HASH_QUOTING 1
#define HAVE_ILOGB 1
#define HAVE_ISINF 1
#define HAVE_ISNAN 1
#define STDC_HEADERS 1
#define HAVE_SINGLEPRECISION_MATH 1
#define HAVE_SNPRINTF 1
#define HAVE_STRNCASECMP 1
#define HAVE_VA_COPY_MACRO 1
#define HAVE_VSNPRINTF 1

#define COIN_THREADID_TYPE pthread_t
#define HAVE_PTHREAD_TIMESPEC_NSEC 1
#define HAVE_THREADS 
#define USE_PTHREAD 
#define HAVE___BUILTIN_EXPECT 1

#define HAVE_X11_AVAILABLE 1

#ifdef OUREX_COINGL_INLIB_GL
#else
#define HAVE_GLX 1
#endif
#define HAVE_GL_GLEXT_H 1
#define HAVE_GL_GL_H 1
#define HAVE_OPENGL 1

#define GLUWRAPPER_ASSUME_GLU 1

/* NOTE : We use ourex/zlib. ourex/HEPVis must be consistent with what is done here.*/
#define HAVE_ZLIB 1
