#!/bin/sh -f

save_dir=`pwd`

bush_home=../../../bush

${bush_home}/check_app _incs '_incs program not found.'
build_status=$?;if [ ${build_status} != 0 ] ; then exit ${build_status};fi

#wcslib_home=../../ourex_zips/wcslib-4.14  #LSST/8.0
wcslib_home=../../ourex_zips/wcslib-4.21

#verbose=-verbose

find ./include -name '*.h' -exec /bin/rm -f {} \;
find ./src -name '*.c' -exec /bin/rm -f {} \;

#exit
#set -x

echo "////////////////////////"
echo "/// wcslib /////////////"
echo "////////////////////////"
to=${save_dir}/include/wcslib
/bin/mkdir -p ${to}
/bin/cp ./modified/wcsconfig.h ./include/wcslib/.
/bin/cp ./modified/wcsconfig.h ./src/.

to=${save_dir}/src
/bin/mkdir -p ${to}
cd ${wcslib_home}/C

dirs="."
dirs="${dirs}:${save_dir}/include/wcslib"

find . -maxdepth 1 -name '*.c' -print -exec _incs ${verbose} -pack -dirs=${dirs} -to=${to} {} \;
find ./flexed -maxdepth 1 -name '*.c' -print -exec _incs ${verbose} -pack -dirs=${dirs} -to=${to} {} \;

cd ${save_dir}
dirs=

find ./src -name '*.h' -exec /bin/mv {} ./include/wcslib/. \;
find ./src/flexed -name '*.c' -exec /bin/mv {} ./src/. \;

/bin/cp ${wcslib_home}/C/wcslib.h ./include/wcslib/.
/bin/mv ./src/getwcstab.c ./src/getwcstab.c_not_in_lib

/bin/rm -R -f ./src/Users
/bin/rm -R -f ./src/flexed

/bin/cp ./modified/wcs.h ./include/wcslib/.
/bin/cp ./modified/wcs.c ./src/.
/bin/cp ./modified/wcsfix.c ./src/.
/bin/cp ./modified/wcshdr.c ./src/.
/bin/cp ./modified/wcsutil.c ./src/.

echo "////////////////////////"
echo "/// tests //////////////"
echo "////////////////////////"
to=${save_dir}/tests
/bin/mkdir -p ${to}

/bin/cp ./modified/wcsconfig_tests.h ./tests/.

find ${wcslib_home}/C/test -name '*.c' -exec /bin/cp {} ./tests/. \;
find ${wcslib_home}/C/test -name '*.out' -exec /bin/cp {} ./tests/. \;

/bin/cp ${wcslib_home}/C/test/pih.keyrec ./tests/.
/bin/cp ${wcslib_home}/C/test/bth.keyrec ./tests/.

/bin/cp ${wcslib_home}/C/test/units_test ./tests/.

find ./tests -name '*' -exec chmod ug+w {} \;

/bin/cp ./modified/tspcspxe.c ./tests/.
/bin/cp ./modified/tsphdpa.c ./tests/.

cd ${save_dir}


