#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

. ../mgr/build_header

cd ${build_path}
./tofits < ../tests/pih.keyrec > ./pih.fits
./tofits < ../tests/bth.keyrec > ./bth.fits

#./tfitshdr

./tunits < ../tests/units_test > tmp_out
if ! cmp -s tmp_out ../tests/tunits.out ; then
  echo 'tunits failed.'
fi

items="tfitshdr"
#items="${items} tbth1"
#items="${items} tbth1 tpih1 twcsfix twcstab twcssub"
for item in ${items} ; do
  ./${item} > tmp_out
  if ! cmp -s tmp_out ../tests/${item}.out ; then
    echo "${item} failed."
  fi
done
