#ifndef HEPVis_HEPVis_gl2ps_h
#define HEPVis_HEPVis_gl2ps_h

/* 
 gl2ps-1.3.2
 The gl2ps code is prefixed by HEPVis_ in order
 to avoid clashes with other gl2ps code that may come at link
 time from other channels.
*/

/* 1.2.3 */

#define gl2psBeginPage HEPVis_gl2psBeginPage
#define gl2psEndPage HEPVis_gl2psEndPage
#define gl2psText HEPVis_gl2psText
#define gl2psEnable HEPVis_gl2psEnable
#define gl2psDisable HEPVis_gl2psDisable
#define gl2psPointSize HEPVis_gl2psPointSize
#define gl2psLineWidth HEPVis_gl2psLineWidth
#define gl2psNumShadeColors HEPVis_gl2psNumShadeColors
#define gl2psDrawPixels HEPVis_gl2psDrawPixels
#define gl2psBeginViewport HEPVis_gl2psBeginViewport
#define gl2psEndViewport HEPVis_gl2psEndViewport

#define gl2psMsg HEPVis_gl2psMsg
#define gl2psMalloc HEPVis_gl2psMalloc
#define gl2psRealloc HEPVis_gl2psRealloc
#define gl2psFree HEPVis_gl2psFree
#define gl2psListRealloc HEPVis_gl2psListRealloc
#define gl2psListCreate HEPVis_gl2psListCreate
#define gl2psListDelete HEPVis_gl2psListDelete
#define gl2psListAdd HEPVis_gl2psListAdd
#define gl2psListNbr HEPVis_gl2psListNbr
#define gl2psListPointer HEPVis_gl2psListPointer
#define gl2psListSort HEPVis_gl2psListSort
#define gl2psListAction HEPVis_gl2psListAction
#define gl2psListActionInverse HEPVis_gl2psListActionInverse
#define gl2psComparePointPlane HEPVis_gl2psComparePointPlane
#define gl2psPsca HEPVis_gl2psPsca
#define gl2psPvec HEPVis_gl2psPvec
#define gl2psNorm HEPVis_gl2psNorm
#define gl2psGetNormal HEPVis_gl2psGetNormal
#define gl2psGetPlane HEPVis_gl2psGetPlane
#define gl2psCutEdge HEPVis_gl2psCutEdge
#define gl2psCreateSplitPrimitive HEPVis_gl2psCreateSplitPrimitive
#define gl2psAddIndex HEPVis_gl2psAddIndex
#define gl2psGetIndex HEPVis_gl2psGetIndex
#define gl2psTestSplitPrimitive HEPVis_gl2psTestSplitPrimitive
#define gl2psSplitPrimitive HEPVis_gl2psSplitPrimitive
#define gl2psDivideQuad HEPVis_gl2psDivideQuad
#define gl2psCompareDepth HEPVis_gl2psCompareDepth
#define gl2psTrianglesFirst HEPVis_gl2psTrianglesFirst
#define gl2psFindRoot HEPVis_gl2psFindRoot
#define gl2psFreePrimitive HEPVis_gl2psFreePrimitive
#define gl2psAddPrimitiveInList HEPVis_gl2psAddPrimitiveInList
#define gl2psFreeBspTree HEPVis_gl2psFreeBspTree
#define gl2psGreater HEPVis_gl2psGreater
#define gl2psLess HEPVis_gl2psLess
#define gl2psBuildBspTree HEPVis_gl2psBuildBspTree
#define gl2psTraverseBspTree HEPVis_gl2psTraverseBspTree
#define gl2psGetPlaneFromPoints HEPVis_gl2psGetPlaneFromPoints
#define gl2psFreeBspImageTree HEPVis_gl2psFreeBspImageTree
#define gl2psCheckPoint HEPVis_gl2psCheckPoint
#define gl2psAddPlanesInBspTreeImage HEPVis_gl2psAddPlanesInBspTreeImage
#define gl2psCheckPrimitive HEPVis_gl2psCheckPrimitive
#define gl2psCreateSplitPrimitive2D HEPVis_gl2psCreateSplitPrimitive2D
#define gl2psSplitPrimitive2D HEPVis_gl2psSplitPrimitive2D
#define gl2psAddInImageTree HEPVis_gl2psAddInImageTree
#define gl2psAddInImage HEPVis_gl2psAddInImage
#define gl2psAddBoundaryInList HEPVis_gl2psAddBoundaryInList
#define gl2psBuildPolygonBoundary HEPVis_gl2psBuildPolygonBoundary
#define gl2psAddPolyPrimitive HEPVis_gl2psAddPolyPrimitive
#define gl2psGetVertex HEPVis_gl2psGetVertex
#define gl2psParseFeedbackBuffer HEPVis_gl2psParseFeedbackBuffer
#define gl2psSameColor HEPVis_gl2psSameColor
#define gl2psVertsSameColor HEPVis_gl2psVertsSameColor
#define gl2psPrintPostScriptHeader HEPVis_gl2psPrintPostScriptHeader
#define gl2psPrintPostScriptColor HEPVis_gl2psPrintPostScriptColor
#define gl2psResetPostScriptColor HEPVis_gl2psResetPostScriptColor
#define gl2psPrintPostScriptPrimitive HEPVis_gl2psPrintPostScriptPrimitive
#define gl2psPrintPostScriptFooter HEPVis_gl2psPrintPostScriptFooter
#define gl2psPrintTeXHeader HEPVis_gl2psPrintTeXHeader
#define gl2psPrintTeXPrimitive HEPVis_gl2psPrintTeXPrimitive
#define gl2psPrintTeXFooter HEPVis_gl2psPrintTeXFooter

#define gl2psPrintPostScriptBeginViewport HEPVis_gl2psPrintPostScriptBeginViewport
#define gl2psPrintPostScriptEndViewport HEPVis_gl2psPrintPostScriptEndViewport

#define gl2psWriteByte HEPVis_gl2psWriteByte
#define gl2psGetRGB HEPVis_gl2psGetRGB
#define gl2psPrintPostScriptPixmap HEPVis_gl2psPrintPostScriptPixmap
#define gl2psListReset HEPVis_gl2psListReset
#define gl2psAddInBspImageTree HEPVis_gl2psAddInBspImageTree
#define gl2psPrintPrimitives HEPVis_gl2psPrintPrimitives
#define gl2psPrintTeXBeginViewport HEPVis_gl2psPrintTeXBeginViewport
#define gl2psPrintTeXEndViewport HEPVis_gl2psPrintTeXEndViewport

#define gl2psAdaptVertexForBlending HEPVis_gl2psAdaptVertexForBlending
#define gl2psAssignTriangleProperties HEPVis_gl2psAssignTriangleProperties
#define gl2psBlendFunc HEPVis_gl2psBlendFunc
#define gl2psClosePDFDataStream HEPVis_gl2psClosePDFDataStream
#define gl2psCopyPixmap HEPVis_gl2psCopyPixmap
#define gl2psCopyPrimitive HEPVis_gl2psCopyPrimitive
#define gl2psCopyText HEPVis_gl2psCopyText
#define gl2psDrawImageMap HEPVis_gl2psDrawImageMap
#define gl2psFillTriangleFromPrimitive HEPVis_gl2psFillTriangleFromPrimitive
#define gl2psFreeImagemap HEPVis_gl2psFreeImagemap
#define gl2psFreePixmap HEPVis_gl2psFreePixmap
#define gl2psFreeText HEPVis_gl2psFreeText
#define gl2psOpenPDFDataStream HEPVis_gl2psOpenPDFDataStream
#define gl2psOpenPDFDataStreamWritePreface HEPVis_gl2psOpenPDFDataStreamWritePreface
#define gl2psPDFRectHull HEPVis_gl2psPDFRectHull
#define gl2psPDFgroupListDelete HEPVis_gl2psPDFgroupListDelete
#define gl2psPDFgroupListInit HEPVis_gl2psPDFgroupListInit
#define gl2psPDFgroupListWriteFontResources HEPVis_gl2psPDFgroupListWriteFontResources
#define gl2psPDFgroupListWriteGStateResources HEPVis_gl2psPDFgroupListWriteGStateResources
#define gl2psPDFgroupListWriteMainStream HEPVis_gl2psPDFgroupListWriteMainStream
#define gl2psPDFgroupListWriteObjects HEPVis_gl2psPDFgroupListWriteObjects
#define gl2psPDFgroupListWriteShaderResources HEPVis_gl2psPDFgroupListWriteShaderResources
#define gl2psPDFgroupListWriteVariableResources HEPVis_gl2psPDFgroupListWriteVariableResources
#define gl2psPDFgroupListWriteXObjectResources HEPVis_gl2psPDFgroupListWriteXObjectResources
#define gl2psPDFgroupObjectInit HEPVis_gl2psPDFgroupObjectInit
#define gl2psPDFstacksInit HEPVis_gl2psPDFstacksInit
#define gl2psPrintPDFBeginViewport HEPVis_gl2psPrintPDFBeginViewport
#define gl2psPrintPDFCatalog HEPVis_gl2psPrintPDFCatalog
#define gl2psPrintPDFCompressorType HEPVis_gl2psPrintPDFCompressorType
#define gl2psPrintPDFDataStreamLength HEPVis_gl2psPrintPDFDataStreamLength
#define gl2psPrintPDFEndViewport HEPVis_gl2psPrintPDFEndViewport
#define gl2psPrintPDFFillColor HEPVis_gl2psPrintPDFFillColor
#define gl2psPrintPDFFooter HEPVis_gl2psPrintPDFFooter
#define gl2psPrintPDFGSObject HEPVis_gl2psPrintPDFGSObject
#define gl2psPrintPDFHeader HEPVis_gl2psPrintPDFHeader
#define gl2psPrintPDFInfo HEPVis_gl2psPrintPDFInfo
#define gl2psPrintPDFLineWidth HEPVis_gl2psPrintPDFLineWidth
#define gl2psPrintPDFOpenPage HEPVis_gl2psPrintPDFOpenPage
#define gl2psPrintPDFPages HEPVis_gl2psPrintPDFPages
#define gl2psPrintPDFPixmap HEPVis_gl2psPrintPDFPixmap
#define gl2psPrintPDFPixmapStreamData HEPVis_gl2psPrintPDFPixmapStreamData
#define gl2psPrintPDFPrimitive HEPVis_gl2psPrintPDFPrimitive
#define gl2psPrintPDFShader HEPVis_gl2psPrintPDFShader
#define gl2psPrintPDFShaderExtGS HEPVis_gl2psPrintPDFShaderExtGS
#define gl2psPrintPDFShaderMask HEPVis_gl2psPrintPDFShaderMask
#define gl2psPrintPDFShaderSimpleExtGS HEPVis_gl2psPrintPDFShaderSimpleExtGS
#define gl2psPrintPDFShaderStreamData HEPVis_gl2psPrintPDFShaderStreamData
#define gl2psPrintPDFShaderStreamDataAlpha HEPVis_gl2psPrintPDFShaderStreamDataAlpha
#define gl2psPrintPDFShaderStreamDataCoord HEPVis_gl2psPrintPDFShaderStreamDataCoord
#define gl2psPrintPDFShaderStreamDataRGB HEPVis_gl2psPrintPDFShaderStreamDataRGB
#define gl2psPrintPDFStrokeColor HEPVis_gl2psPrintPDFStrokeColor
#define gl2psPrintPDFText HEPVis_gl2psPrintPDFText
#define gl2psPrintPostScriptImagemap HEPVis_gl2psPrintPostScriptImagemap
#define gl2psPrintf HEPVis_gl2psPrintf
#define gl2psPutPDFImage HEPVis_gl2psPutPDFImage
#define gl2psPutPDFText HEPVis_gl2psPutPDFText
#define gl2psSetLastColor HEPVis_gl2psSetLastColor
#define gl2psSortOutTrianglePDFgroup HEPVis_gl2psSortOutTrianglePDFgroup
#define gl2psSupportedBlendMode HEPVis_gl2psSupportedBlendMode
#define gl2psTextOpt HEPVis_gl2psTextOpt
#define gl2psWriteBigEndian HEPVis_gl2psWriteBigEndian
#define gl2psPrintDash HEPVis_gl2psPrintDash
#define gl2psRescaleAndOffset HEPVis_gl2psRescaleAndOffset

#define gl2psGetOptions HEPVis_gl2psGetOptions

/* 1.3.2 */

#define gl2psAddText HEPVis_gl2psAddText
#define gl2psComputeTightBoundingBox HEPVis_gl2psComputeTightBoundingBox
#define gl2psEPS HEPVis_gl2psEPS
#define gl2psEndPostScriptLine HEPVis_gl2psEndPostScriptLine
#define gl2psEndSVGLine HEPVis_gl2psEndSVGLine
#define gl2psGetFileExtension HEPVis_gl2psGetFileExtension
#define gl2psGetFormatDescription HEPVis_gl2psGetFormatDescription
#define gl2psInitTriangle HEPVis_gl2psInitTriangle
#define gl2psPDF HEPVis_gl2psPDF
#define gl2psPGF HEPVis_gl2psPGF
#define gl2psPGFTextAlignment HEPVis_gl2psPGFTextAlignment
#define gl2psPS HEPVis_gl2psPS
#define gl2psParseStipplePattern HEPVis_gl2psParseStipplePattern
#define gl2psPrintGzipFooter HEPVis_gl2psPrintGzipFooter
#define gl2psPrintGzipHeader HEPVis_gl2psPrintGzipHeader
#define gl2psPrintPDFFinalPrimitive HEPVis_gl2psPrintPDFFinalPrimitive
#define gl2psPrintPGFBeginViewport HEPVis_gl2psPrintPGFBeginViewport
#define gl2psPrintPGFColor HEPVis_gl2psPrintPGFColor
#define gl2psPrintPGFDash HEPVis_gl2psPrintPGFDash
#define gl2psPrintPGFEndViewport HEPVis_gl2psPrintPGFEndViewport
#define gl2psPrintPGFFinalPrimitive HEPVis_gl2psPrintPGFFinalPrimitive
#define gl2psPrintPGFFooter HEPVis_gl2psPrintPGFFooter
#define gl2psPrintPGFHeader HEPVis_gl2psPrintPGFHeader
#define gl2psPrintPGFPrimitive HEPVis_gl2psPrintPGFPrimitive
#define gl2psPrintPostScriptDash HEPVis_gl2psPrintPostScriptDash
#define gl2psPrintPostScriptFinalPrimitive HEPVis_gl2psPrintPostScriptFinalPrimitive
#define gl2psPrintSVGBeginViewport HEPVis_gl2psPrintSVGBeginViewport
#define gl2psPrintSVGDash HEPVis_gl2psPrintSVGDash
#define gl2psPrintSVGEndViewport HEPVis_gl2psPrintSVGEndViewport
#define gl2psPrintSVGFinalPrimitive HEPVis_gl2psPrintSVGFinalPrimitive
#define gl2psPrintSVGFooter HEPVis_gl2psPrintSVGFooter
#define gl2psPrintSVGHeader HEPVis_gl2psPrintSVGHeader
#define gl2psPrintSVGPixmap HEPVis_gl2psPrintSVGPixmap
#define gl2psPrintSVGPrimitive HEPVis_gl2psPrintSVGPrimitive
#define gl2psPrintSVGSmoothTriangle HEPVis_gl2psPrintSVGSmoothTriangle
#define gl2psPrintTeXFinalPrimitive HEPVis_gl2psPrintTeXFinalPrimitive
#define gl2psSVG HEPVis_gl2psSVG
#define gl2psSVGGetColorString HEPVis_gl2psSVGGetColorString
#define gl2psSVGGetCoordsAndColors HEPVis_gl2psSVGGetCoordsAndColors
#define gl2psSameColorThreshold HEPVis_gl2psSameColorThreshold
#define gl2psSamePosition HEPVis_gl2psSamePosition
#define gl2psSetOptions HEPVis_gl2psSetOptions
#define gl2psSpecial HEPVis_gl2psSpecial
#define gl2psTEX HEPVis_gl2psTEX
#define gl2psbackends HEPVis_gl2psbackends

#define gl2ps HEPVis_gl2ps

#include "gl2ps.h"

#endif
