#!/bin/sh -f

sophya_src=../../ourex_zips/SrcSophyaV2_300

#///////////////////////////////////////////
#/// get .c, .cc files : ///////////////////
#///////////////////////////////////////////

find ./src -name '*.c' -exec /bin/rm -f {} \;
find ./src -name '*.cc' -exec /bin/rm -f {} \;

# for exlib/examples/cpp/sophya :
cp ${sophya_src}/BaseTools/datatype.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/dvlist.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/fiondblock.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/gnumd5.c ./src/BaseTools/.
cp ${sophya_src}/BaseTools/mutyv.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/ndatablock.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/pexceptions.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/ppersist.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/ppfbinstream.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/ppftpointerio.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/rawstream.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/stsrand.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/randr48.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/timestamp.cc ./src/BaseTools/.

cp ${sophya_src}/SUtils/strutil.c ./src/SUtils/.
cp ${sophya_src}/HiStats/basedtable.cc ./src/HiStats/.
cp ${sophya_src}/HiStats/datatable.cc ./src/HiStats/.
cp ${sophya_src}/HiStats/ntupintf.cc ./src/HiStats/.
cp ${sophya_src}/HiStats/ntuple.cc ./src/HiStats/.
cp ${sophya_src}/HiStats/swppfdtable.cc ./src/HiStats/.
cp ${sophya_src}/FitsIOServer/fitsbntbllineRW.cc ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitsfile.cc ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitshdtable.cc ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitsinoutfile.cc ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitsntuple.cc ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/swfitsdtable.cc ./src/FitsIOServer/.
cp ${sophya_src}/TArray/basarr.cc ./src/TArray/.
cp ${sophya_src}/TArray/tarray.cc ./src/TArray/.
cp ${sophya_src}/TArray/tmatrix.cc ./src/TArray/.
cp ${sophya_src}/TArray/tvector.cc ./src/TArray/.
cp ${sophya_src}/TArray/utilarr.cc ./src/TArray/.

# for exlib/examples/cpp/sophya :
cp ${sophya_src}/FitsIOServer/fitsmanager.cc ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitshistos.cc ./src/FitsIOServer/.
cp ${sophya_src}/HiStats/hisprof.cc ./src/HiStats/.
cp ${sophya_src}/HiStats/histos2.cc ./src/HiStats/.
cp ${sophya_src}/HiStats/histos.cc ./src/HiStats/.
cp ${sophya_src}/TArray/fioarr.cc ./src/TArray/.
cp ${sophya_src}/TArray/sopemtx.cc ./src/TArray/.
cp ${sophya_src}/NTools/poly.cc ./src/NTools/.

# V2_3 :
cp ${sophya_src}/BaseTools/sunitpcst.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/pqnumber.cc ./src/BaseTools/.
cp ${sophya_src}/BaseTools/randinterf.cc ./src/BaseTools/.
cp ${sophya_src}/HiStats/dtcellrowcont.cc ./src/HiStats/.

cp ./modified/ppfbinstream.cc ./src/BaseTools/.
cp ./modified/basedtable.cc ./src/HiStats/.
cp ./modified/fitsfile.cc ./src/FitsIOServer/.
cp ./modified/fitsbntbllineRW.cc ./src/FitsIOServer/.
cp ./modified/fitsntuple.cc ./src/FitsIOServer/.
cp ./modified/fitsinoutfile.cc ./src/FitsIOServer/.

#cp ${sophya_src}/BaseTools/sophyainit.cc ./src/BaseTools/.
#cp ${sophya_src}/BaseTools/srandgen.c ./src/BaseTools/.
#cp ${sophya_src}/SUtils/datacards.cc ./src/SUtils/.
#cp ${sophya_src}/SUtils/strutilxx.cc ./src/SUtils/.
#cp ${sophya_src}/SUtils/utils.cc ./src/SUtils/.

#cp ${sophya_src}/HiStats/fio_dtable.cc ./src/HiStats/.
#cp ${sophya_src}/HiStats/hist2err.cc ./src/HiStats/.
#cp ${sophya_src}/HiStats/histerr.cc ./src/HiStats/.
#cp ${sophya_src}/HiStats/histinit.cc ./src/HiStats/.
#cp ${sophya_src}/HiStats/proxtuple.cc ./src/HiStats/.
#cp ${sophya_src}/HiStats/xntuple.cc ./src/HiStats/.

#cp ${sophya_src}/FitsIOServer/datacirclefits.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fabtcolread.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fabtwriter.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fboloread.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fbtntintf.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fiosinit.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fitsautoreader.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fitsgenedata.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fitshisterr.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fitslocalmap.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fitsspherehealpix.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fitsspherethetaphi.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fitstarray.cc ./src/FitsIOServer/.
#cp ${sophya_src}/FitsIOServer/fitsxntuple.cc ./src/FitsIOServer/.
#cp ${sophya_src}/TArray/matharr.cc ./src/TArray/.
#cp ${sophya_src}/TArray/tarrinit.cc ./src/TArray/.

#cp ${sophya_src}/NTools/cimage.cc ./src/NTools/.
#cp ${sophya_src}/NTools/cspline.cc ./src/NTools/.
#cp ${sophya_src}/NTools/datatypes.cc ./src/NTools/.
#cp ${sophya_src}/NTools/dates.cc ./src/NTools/.
#cp ${sophya_src}/NTools/datime.c ./src/NTools/.
#cp ${sophya_src}/NTools/difeq.cc ./src/NTools/.
#cp ${sophya_src}/NTools/dynccd.cc ./src/NTools/.
#cp ${sophya_src}/NTools/fct1dfit.cc ./src/NTools/.
#cp ${sophya_src}/NTools/fct2dfit.cc ./src/NTools/.
#cp ${sophya_src}/NTools/fftmayer_r4.c ./src/NTools/.
#cp ${sophya_src}/NTools/fftmayer_r8.c ./src/NTools/.
#cp ${sophya_src}/NTools/fftmserver.cc ./src/NTools/.
#cp ${sophya_src}/NTools/fftpackc.c ./src/NTools/.
#cp ${sophya_src}/NTools/fftpserver.cc ./src/NTools/.
#cp ${sophya_src}/NTools/fftservintf.cc ./src/NTools/.
#cp ${sophya_src}/NTools/FSAppIrrSmpl.cc ./src/NTools/.
#cp ${sophya_src}/NTools/functab.cc ./src/NTools/.
#cp ${sophya_src}/NTools/generaldata.cc ./src/NTools/.
#cp ${sophya_src}/NTools/generalfit.cc ./src/NTools/.
#cp ${sophya_src}/NTools/generalfunc.cc ./src/NTools/.
#cp ${sophya_src}/NTools/integ.cc ./src/NTools/.
#cp ${sophya_src}/NTools/matxop.c ./src/NTools/.
#cp ${sophya_src}/NTools/median.cc ./src/NTools/.
#cp ${sophya_src}/NTools/nbmath.c ./src/NTools/.
#cp ${sophya_src}/NTools/nbtri.c ./src/NTools/.
#cp ${sophya_src}/NTools/ntoolsinit.cc ./src/NTools/.
#cp ${sophya_src}/NTools/objfitter.cc ./src/NTools/.
#cp ${sophya_src}/NTools/perandom.cc ./src/NTools/.
#cp ${sophya_src}/NTools/rk4cdifeq.cc ./src/NTools/.
#cp ${sophya_src}/NTools/simplesort.cc ./src/NTools/.
#cp ${sophya_src}/NTools/simplex.cc ./src/NTools/.
#cp ${sophya_src}/NTools/tabmath.cc ./src/NTools/.
#cp ${sophya_src}/NTools/toeplitzMatrix.cc ./src/NTools/.

#cp ${sophya_src}/Samba/circle.cc ./src/Samba/.

#///////////////////////////////////////////
#/// get .h : //////////////////////////////
#///////////////////////////////////////////
find ./src -name '*.h' -exec /bin/rm -f {} \;
find ./include -name '*.h' -exec /bin/rm -f {} \;

# for exlib/examples/cpp/sophya :
cp ${sophya_src}/BaseTools/gnumd5.h ./src/BaseTools/.
cp ${sophya_src}/SUtils/strutil.h ./src/SUtils/.
cp ${sophya_src}/BaseTools/datatype.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/dvlist.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/fiondblock.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/mutyv.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/ndatablock.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/pexceptions.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/ppersist.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/ppfbinstream.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/ppftpointerio.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/rawstream.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/stsrand.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/timestamp.h ./src/BaseTools/.
cp ${sophya_src}/FitsIOServer/fitsbntbllineRW.h ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitsfile.h ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitshdtable.h ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitsinoutfile.h ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitsntuple.h ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitsmanager.h ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/swfitsdtable.h ./src/FitsIOServer/.
cp ${sophya_src}/HiStats/basedtable.h ./src/HiStats/.
cp ${sophya_src}/HiStats/datatable.h ./src/HiStats/.
cp ${sophya_src}/HiStats/ntupintf.h ./src/HiStats/.
cp ${sophya_src}/HiStats/ntuple.h ./src/HiStats/.
cp ${sophya_src}/HiStats/swppfdtable.h ./src/HiStats/.
cp ${sophya_src}/TArray/basarr.h ./src/TArray/.
cp ${sophya_src}/TArray/tarray.h ./src/TArray/.
cp ${sophya_src}/TArray/tmatrix.h ./src/TArray/.
cp ${sophya_src}/TArray/tvector.h ./src/TArray/.
cp ${sophya_src}/TArray/utilarr.h ./src/TArray/.
cp ${sophya_src}/NTools/poly.h ./src/NTools/.

# extra headers :
cp ${sophya_src}/BaseTools/bithelp.h ./include/.
cp ${sophya_src}/BaseTools/sopnamsp.h ./include/.
cp ${sophya_src}/BaseTools/objfio.h ./include/.
cp ${sophya_src}/BaseTools/anydataobj.h ./include/.
cp ${sophya_src}/BaseTools/ppfnametag.h ./include/.
cp ${sophya_src}/BaseTools/segdatablock.h ./include/.
cp ${sophya_src}/TArray/tmatrix_tsnl.h ./include/.
cp ${sophya_src}/TArray/tvector_tsnl.h ./include/.
cp ${sophya_src}/BaseTools/fiosegdb.h ./include/.
cp ${sophya_src}/BaseTools/thsafeop.h ./include/.
cp ${sophya_src}/BaseTools/perrors.h ./include/.
cp ${sophya_src}/BaseTools/swsegdb.h ./include/.
cp ${sophya_src}/BaseTools/ppfswapper.h ./include/.
cp ${sophya_src}/SUtils/utils.h ./include/.
cp ${sophya_src}/FitsIOServer/fitshandler.h ./include/.
cp ${sophya_src}/FitsIOServer/fitsswapper.h ./include/.
cp ${sophya_src}/FitsIOServer/fitsblkrw.h ./include/.

# for exlib/examples/cpp/sophya_2 :
cp ${sophya_src}/FitsIOServer/fitsmanager.h ./src/FitsIOServer/.
cp ${sophya_src}/HiStats/histos.h ./src/HiStats/.
cp ${sophya_src}/HiStats/histos2.h ./src/HiStats/.
cp ${sophya_src}/HiStats/hisprof.h ./src/HiStats/.
cp ${sophya_src}/TArray/fioarr.h ./src/TArray/.
cp ${sophya_src}/TArray/sopemtx.h ./src/TArray/.

cp ${sophya_src}/FitsIOServer/fitsarrhand.h ./include/.
cp ${sophya_src}/NTools/fmath.h ./include/.
cp ${sophya_src}/NTools/linfit.h ./include/.
cp ${sophya_src}/NTools/peida.h ./include/.
cp ${sophya_src}/BaseTools/smathconst.h ./include/.

find ./src -name '*.h' -exec /bin/cp {} ./include/. \;

# V2_3 :
cp ${sophya_src}/BaseTools/sunitpcst.h ./include/.
cp ${sophya_src}/BaseTools/pqnumber.h ./include/.
cp ${sophya_src}/BaseTools/randinterf.h ./include/.
cp ${sophya_src}/BaseTools/swppfsegdb.h ./include/.
cp ${sophya_src}/BaseTools/randr48.h ./include/.
cp ${sophya_src}/HiStats/dtcellrowcont.h ./include/.
cp ${sophya_src}/SUtils/fmlstr.h ./include/.
cp ${sophya_src}/SUtils/ppfpio_fmls.h ./include/.

cp ${sophya_src}/BaseTools/sunitpcst.h ./src/BaseTools/.
cp ${sophya_src}/BaseTools/pqnumber.h ./src/BaseTools/.

cp ./modified/machdefs.h ./include/.
cp ./modified/fitsinoutfile.h ./src/FitsIOServer/.
cp ./modified/fitsinoutfile.h ./include/.

cp ./modified/ntupintf.h ./include/.
cp ./modified/ntupintf.h ./src/HiStats/.

cp ./modified/swppfdtable.h ./src/HiStats/.

cp ./modified/sunitpcst.h ./include/.
cp ./modified/sunitpcst.h ./src/BaseTools/.

cp ./modified/ppersist.h ./include/.

#WIN32 :

cp ./modified/fitsarrhand.h ./include/.

cp ./modified/histos.cc ./src/HiStats/.

cp ./modified/ndatablock.cc ./src/BaseTools/.

# HDF5 :
cp ./modified/basedtable.cc ./src/HiStats/.
cp ./modified/basedtable.h ./src/HiStats/.
cp ./modified/basedtable.h ./include/.

#///////////////////////////////////////////
#/// SkyMap : //////////////////////////////
#///////////////////////////////////////////
find ${sophya_src}/SkyMap -maxdepth 1 -name '*.cc' -exec /bin/cp {} ./src/SkyMap/. \;
find ${sophya_src}/SkyMap -maxdepth 1 -name '*.h'  -exec /bin/cp {} ./include/. \;
/bin/rm -f ./include/skymapinit.h
/bin/rm -f ./src/SkyMap/skymapinit.cc
cp ${sophya_src}/SysTools/timing.c ./src/SysTools/.
cp ${sophya_src}/SysTools/timing.h ./include/.

cp ${sophya_src}/Tests/sphg0.cc ./apps/.

cp ./modified/utilarr.h ./include/.
cp ./modified/HEALPixUtils.cc ./src/SkyMap/.

cp ${sophya_src}/Tests/sph2lm.cc ./apps/.
#cp ${sophya_src}/NTools/cimage.cc ./src/NTools/.
#cp ${sophya_src}/NTools/cimage.h ./include/.
cp ./modified/sph2lm.cc ./apps/.

# for sph2asc.cc :
cp ${sophya_src}/FitsIOServer/fitsspherehealpix.cc ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitsspherehealpix.h ./include/.
cp ${sophya_src}/FitsIOServer/fitstarray.cc ./src/FitsIOServer/.
cp ${sophya_src}/FitsIOServer/fitstarray.h ./include/.

#///////////////////////////////////////////
#/// commands : ////////////////////////////
#///////////////////////////////////////////
cp ${sophya_src}/Tests/tcmd.cc ./apps/.
files="commander cexpre rpneval pdlmgr ctimer zthread"
for file in ${files} ; do
  cp ${sophya_src}/SysTools/${file}.cc ./src/SysTools/.
  cp ${sophya_src}/SysTools/${file}.h ./include/.
done
cp ${sophya_src}/BaseTools/srandgen.h ./include/.
cp ${sophya_src}/SUtils/strutilxx.cc ./src/SUtils/.
cp ${sophya_src}/SUtils/strutilxx.h ./include/.

cp ./modified/tcmd.cc ./apps/.
cp ./modified/sphg0.cc ./apps/.

cp ./modified/commander.cc ./src/SysTools/.
cp ./modified/pdlmgr.cc ./src/SysTools/.

