#!/bin/sh -f

from=$2
to=$3

dirname=`dirname $1`
basename=`basename $1`

todir=`echo $dirname | sed -e "s|${from}|${to}|g"`
toname=`echo $basename`

#echo $todir
#echo $toname
#exit

cp $1 "${todir}"/${toname}
exit

#sed -e 's||""|g' $1 > tmp
#/bin/mv tmp ${todir}/${toname}
