#!/bin/sh -f

dirname=`dirname $1`
basename=`basename $1`

toname=`echo $basename | sed -e 's:.glsl:.h:g'`

set -x
echo ++++++++
echo $1
echo ${dirname}/${toname}
./glsl2h.sh $1 > ${dirname}/${toname}




