#!/bin/sh -f

#set -x

from=/Users/barrand/dev/externals/Coin-2.5.0
to="/Users/barrand/dev/OpenScientist/head dev/CoinGL/v1r250p0"

find ${from}/src -name "*.cpp" -exec ./cp_cpp {} ${from} "${to}" \;
find ${from}/src -name "*.c" -exec ./cp_cpp {} ${from} "${to}" \;
find ${from}/src -name "*.h" -exec ./cp_cpp {} ${from} "${to}" \;
find ${from}/src -name "*.icc" -exec ./cp_cpp {} ${from} "${to}" \;
find ${from}/src -name "*.ic" -exec ./cp_cpp {} ${from} "${to}" \;

/bin/rm -f ../src/fonts/extractfont.cpp
/bin/rm -f ../src/threads/wrappers.cpp

/bin/mv ../src/glue/freetype.c ../src/glue/freetype_glue.c
/bin/mv ../src/glue/glue-dummy.cpp ../src/glue/glue_dummy.cpp
/bin/mv ../src/threads/common.c ../src/threads/common_threads.c
/bin/mv ../src/threads/threads-dummy.cpp ../src/threads/threads_dummy.cpp
/bin/mv ../src/coin-dummy.cpp ../src/coin_dummy.cpp

find ../src -name 'all-*.cpp' -exec /bin/rm {} \;
find ../src -name 'all*.c' -exec /bin/rm {} \;

#exit

#/////////////////////
#// draggerDefaults :
#/////////////////////
find ${from}/data/draggerDefaults -name "*.iv" -exec ./cp_cpp {} ${from} "${to}" \;
find ${from}/data/draggerDefaults -name "*.h" -exec ./cp_cpp {} ${from} "${to}" \;

cp ${from}/data/draggerDefaults/iv2h.sh.in iv2h.sh
chmod a+x ./iv2h.sh
find ../data/draggerDefaults -name '*.iv' -exec ./cp_iv2h {} \;

#exit

#/////////////////////
#// shaders :
#/////////////////////
find ${from}/data/shaders -name "*.glsl" -exec ./cp_cpp {} ${from} "${to}" \;

cp ${from}/data/shaders/glsl2h.sh.in glsl2h.sh
chmod a+x ./glsl2h.sh
find ../data/shaders -name '*.glsl' -exec ./cp_glsl2h {} \;


