#!/bin/sh -f

from=/Users/barrand/dev/externals/Coin-2.5.0
to="/Users/barrand/dev/OpenScientist/head dev/CoinGL/v1r250p0"

find ${from}/include/Inventor -name "*.h" -exec ./cp_h {} ${from} "${to}" \;

cp ${from}/include/SoWinEnterScope.h ../include/.
cp ${from}/include/SoWinLeaveScope.h ../include/.

cp ${from}/include/SoDebug.h ../include/.

cp ${from}/include/coindefs.h ../src/.
cp ${from}/include/unconfig.h ../src/.

#cp ${from}/include/config.h ../src/.

echo "You have to look basic.h, SbBasic.h, system/inttypes.h(.in) by hand."

exit

cp ${from}/include/Inventor/lock/*.h ../include/Inventor/lock/.
cp ${from}/include/Inventor/system/*.h ../include/Inventor/system/.
cp ${from}/include/Inventor/*.h ../include/Inventor/.
cp ${from}/include/Inventor/misc/*.h ../include/Inventor/misc/.
cp ${from}/include/Inventor/VRMLnodes/*.h ../include/Inventor/VRMLnodes/.
cp ${from}/include/Inventor/actions/*.h ../include/Inventor/actions/.
cp ${from}/include/Inventor/bundles/*.h ../include/Inventor/bundles/.
cp ${from}/include/Inventor/caches/*.h ../include/Inventor/caches/.
cp ${from}/include/Inventor/details/*.h ../include/Inventor/details/.
cp ${from}/include/Inventor/draggers/*.h ../include/Inventor/draggers/.
cp ${from}/include/Inventor/elements/*.h ../include/Inventor/elements/.
cp ${from}/include/Inventor/engines/*.h ../include/Inventor/engines/.
cp ${from}/include/Inventor/errors/*.h ../include/Inventor/errors/.
cp ${from}/include/Inventor/events/*.h ../include/Inventor/events/.
cp ${from}/include/Inventor/fields/*.h ../include/Inventor/fields/.
cp ${from}/include/Inventor/manips/*.h ../include/Inventor/manips/.
cp ${from}/include/Inventor/lists/*.h ../include/Inventor/lists/.
cp ${from}/include/Inventor/nodekits/*.h ../include/Inventor/nodekits/.
cp ${from}/include/Inventor/nodes/*.h ../include/Inventor/nodes/.
cp ${from}/include/Inventor/projectors/*.h ../include/Inventor/projectors/.
cp ${from}/include/Inventor/sensors/*.h ../include/Inventor/sensors/.

